### ISSUE TITLE
Load the module by browser

### ISSUE THREAD

**Issue by danijmj** [tkhquang/vue-simple-accordion#13]
Hi! First thanks for the module,
I have a Doubt, I want to use your vue component in a installation of vue from CDN (In a script tag)
The question is that I don't know how to include your component in my project, and I need help.
Thanks so much!

**Comment by tkhquang** [comment]
> Hi! First thanks for the module,
> I have a Doubt, I want to use your vue component in a installation of vue from CDN (In a script tag)
> The question is that I don't know how to include your component in my project, and I need help.
> Thanks so much!


Hi, sorry for late response, you can follow this jsbin:
https://jsbin.com/kuxotunijo/edit?output

**Comment by danijmj** [comment]
It works!
Thanks for your help.
king Regards!
